run:
  timeout: 5m
  tests: true
  build-tags: []
  skip-dirs:
    - vendor
    - other

output:
  format: colored-line-number
  print-issued-lines: true
  print-linter-name: true

linters-settings:
  errcheck:
    check-type-assertions: true
    check-blank: true
  
  govet:
    enable-all: true
  
  gofmt:
    simplify: true
  
  goimports:
    local-prefixes: go-demo
  
  goconst:
    min-len: 3
    min-occurrences: 3
  
  gocritic:
    enabled-tags:
      - diagnostic
      - style
      - performance
      - experimental
  
  gocyclo:
    min-complexity: 15
  
  godot:
    scope: all
  
  misspell:
    locale: US
  
  nakedret:
    max-func-lines: 30
  
  prealloc:
    simple: true
    range-loops: true
    for-loops: true
  
  revive:
    rules:
      - name: blank-imports
      - name: context-as-argument
      - name: context-keys-type
      - name: dot-imports
      - name: error-return
      - name: error-strings
      - name: error-naming
      - name: exported
      - name: if-return
      - name: increment-decrement
      - name: var-naming
      - name: var-declaration
      - name: package-comments
      - name: range
      - name: receiver-naming
      - name: time-naming
      - name: unexported-return
      - name: indent-error-flow
      - name: errorf
      - name: empty-block
      - name: superfluous-else
      - name: unused-parameter
      - name: unreachable-code
      - name: redefines-builtin-id
  
  staticcheck:
    checks: ["all"]
  
  unused:
    check-exported: false
  
  unparam:
    check-exported: false

linters:
  disable-all: true
  enable:
    - errcheck
    - gosimple
    - govet
    - ineffassign
    - staticcheck
    - unused
    - gofmt
    - goimports
    - goconst
    - gocritic
    - gocyclo
    - godot
    - misspell
    - nakedret
    - prealloc
    - revive
    - typecheck
    - unconvert
    - unparam
    - whitespace

issues:
  exclude-use-default: false
  max-issues-per-linter: 0
  max-same-issues: 0
  
  exclude-rules:
    - path: _test\.go
      linters:
        - errcheck
        - goconst
        - gocyclo
    
    - linters:
        - govet
      text: "shadow: declaration of \"err\""
    
    - linters:
        - revive
      text: "don't use an underscore in package name"

severity:
  default-severity: error

